apiVersion: v1
kind: Namespace
metadata:
  name: campustrade
  labels:
    app.kubernetes.io/name: campustrade
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
