/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fcf9f8",
        "tertiary-fixed-dim": "#27e199",
        "primary-fixed": "#ffdbcd",
        "on-secondary-fixed-variant": "#454748",
        "secondary-fixed": "#e1e3e4",
        "surface-container-high": "#eae7e7",
        "secondary-container": "#e1e3e4",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        secondary: "#5c5f60",
        "primary-container": "#ff6b1a",
        "on-primary-fixed": "#360f00",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "surface-container-low": "#f6f3f2",
        "surface-container-highest": "#e4e2e1",
        "on-primary-container": "#591e00",
        "on-secondary": "#ffffff",
        tertiary: "#006c46",
        "on-background": "#1b1c1c",
        "outline-variant": "#e2bfb2",
        primary: "#a43e00",
        "secondary-fixed-dim": "#c5c7c8",
        "on-tertiary-fixed": "#002112",
        "on-primary-fixed-variant": "#7d2d00",
        "on-secondary-container": "#626566",
        outline: "#8e7165",
        "inverse-surface": "#303030",
        "inverse-primary": "#ffb596",
        "tertiary-container": "#00af74",
        "surface-container": "#f0eded",
        "surface-bright": "#fcf9f8",
        "tertiary-fixed": "#54feb3",
        "surface-variant": "#e4e2e1",
        surface: "#fcf9f8",
        "on-secondary-fixed": "#191c1d",
        "surface-dim": "#dcd9d9",
        "on-surface": "#1b1c1c",
        "inverse-on-surface": "#f3f0f0",
        "surface-tint": "#a43e00",
        "on-surface-variant": "#5a4137",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#005234",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#003a23",
        "primary-fixed-dim": "#ffb596",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px",
        "container-max": "1280px",
        lg: "48px",
        md: "24px",
        xs: "8px",
        base: "4px",
        sm: "16px",
        gutter: "24px",
      },
      fontFamily: {
        "body-lg": ["Manrope"],
        "body-sm": ["Manrope"],
        h2: ["Epilogue"],
        h3: ["Epilogue"],
        "body-md": ["Manrope"],
        "label-caps": ["Manrope"],
        h1: ["Epilogue"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        h2: ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
