apiVersion: v1
kind: ConfigMap
metadata:
  name: campustrade-config
  namespace: campustrade
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "campustrade"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  FRONTEND_URL: "https://campustrade.cm"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  LISTING_SERVICE_URL: "http://listing-service:3003"
  CHAT_SERVICE_URL: "http://chat-service:3004"
  ADMIN_SERVICE_URL: "http://admin-service:3005"
  AI_SERVICE_URL: "http://ai-service:3006"
  SEARCH_SERVICE_URL: "http://search-service:3007"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3008"
