apiVersion: v1
kind: Secret
metadata:
  name: campustrade-secrets
  namespace: campustrade
type: Opaque
stringData:
  DB_USER: "campustrade"
  DB_PASSWORD: "campustrade_pass"
  JWT_SECRET: "campustrade_secret"
  SMTP_USER: ""
  SMTP_PASS: ""
